In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
from datetime import datetime
import plotly.express as px

In [3]:
df1=pd.read_csv('final_data1.csv')
df1.head()

,Unnamed: 0,Name,Inspection_Date,Description,City,Longitude,Latitude,Inspection_Type,Inspection_Score,Inspection_Result,Inspection_Closed_Business,Violation_Type,Violation_Description,Violation_Points,Grade
0,0,#807 TUTTA BELLA,08/31/2022,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,BLUE,"3200 - Insects, rodents, animals not present; ...",5,1.0
1,1,#807 TUTTA BELLA,08/31/2022,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,RED,0200 - Food Worker Cards current for all food ...,5,1.0
2,2,#807 TUTTA BELLA,01/13/2022,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0
3,3,#807 TUTTA BELLA,01/06/2021,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0
4,4,+MAS CAFE,07/13/2022,Seating 0-12 - Risk Category III,SEATTLE,-122.334587,47.648180,Return Inspection,0.0,Satisfactory,False,No_card,No_violation,0,2.0

In [4]:
df1['Inspection_Date'] = pd.to_datetime(df1['Inspection_Date'])
df1.head()

,Unnamed: 0,Name,Inspection_Date,Description,City,Longitude,Latitude,Inspection_Type,Inspection_Score,Inspection_Result,Inspection_Closed_Business,Violation_Type,Violation_Description,Violation_Points,Grade
0,0,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,BLUE,"3200 - Insects, rodents, animals not present; ...",5,1.0
1,1,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,RED,0200 - Food Worker Cards current for all food ...,5,1.0
2,2,#807 TUTTA BELLA,2022-01-13,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0
3,3,#807 TUTTA BELLA,2021-01-06,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0
4,4,+MAS CAFE,2022-07-13,Seating 0-12 - Risk Category III,SEATTLE,-122.334587,47.648180,Return Inspection,0.0,Satisfactory,False,No_card,No_violation,0,2.0

In [5]:
df1['Year'] = pd.DatetimeIndex(df1['Inspection_Date']).year
df1['Month'] = pd.DatetimeIndex(df1['Inspection_Date']).month
df1['day_of_week'] = df1['Inspection_Date'].dt.day_name()
df1.head()

,Unnamed: 0,Name,Inspection_Date,Description,City,Longitude,Latitude,Inspection_Type,Inspection_Score,Inspection_Result,Inspection_Closed_Business,Violation_Type,Violation_Description,Violation_Points,Grade,Year,Month,day_of_week
0,0,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,BLUE,"3200 - Insects, rodents, animals not present; ...",5,1.0,2022,8,Wednesday
1,1,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,RED,0200 - Food Worker Cards current for all food ...,5,1.0,2022,8,Wednesday
2,2,#807 TUTTA BELLA,2022-01-13,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0,2022,1,Thursday
3,3,#807 TUTTA BELLA,2021-01-06,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0,2021,1,Wednesday
4,4,+MAS CAFE,2022-07-13,Seating 0-12 - Risk Category III,SEATTLE,-122.334587,47.648180,Return Inspection,0.0,Satisfactory,False,No_card,No_violation,0,2.0,2022,7,Wednesday

In [6]:
def find_season(month, hemisphere):
    if hemisphere == 'Southern':
        season_month_south = {
            12:'Summer', 1:'Summer', 2:'Summer',
            3:'Autumn', 4:'Autumn', 5:'Autumn',
            6:'Winter', 7:'Winter', 8:'Winter',
            9:'Spring', 10:'Spring', 11:'Spring'}
        return season_month_south.get(month)
        
    elif hemisphere == 'Northern':
        season_month_north = {
            12:'Winter', 1:'Winter', 2:'Winter',
            3:'Spring', 4:'Spring', 5:'Spring',
            6:'Summer', 7:'Summer', 8:'Summer',
            9:'Autumn', 10:'Autumn', 11:'Autumn'}
        return season_month_north.get(month)
    else:
        print('Invalid selection. Please select a hemisphere and try again')

In [7]:

season_list = []
hemisphere = 'Northern'
for month in df1['Month']:
    season = find_season(month, hemisphere)
    season_list.append(season)
    
df1['Season'] = season_list
df1.head()

,Unnamed: 0,Name,Inspection_Date,Description,City,Longitude,Latitude,Inspection_Type,Inspection_Score,Inspection_Result,Inspection_Closed_Business,Violation_Type,Violation_Description,Violation_Points,Grade,Year,Month,day_of_week,Season
0,0,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,BLUE,"3200 - Insects, rodents, animals not present; ...",5,1.0,2022,8,Wednesday,Summer
1,1,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,RED,0200 - Food Worker Cards current for all food ...,5,1.0,2022,8,Wednesday,Summer
2,2,#807 TUTTA BELLA,2022-01-13,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0,2022,1,Thursday,Winter
3,3,#807 TUTTA BELLA,2021-01-06,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0,2021,1,Wednesday,Winter
4,4,+MAS CAFE,2022-07-13,Seating 0-12 - Risk Category III,SEATTLE,-122.334587,47.648180,Return Inspection,0.0,Satisfactory,False,No_card,No_violation,0,2.0,2022,7,Wednesday,Summer

In [8]:
#حذف ستون های Unnamed
full=pd.read_csv('full.csv',index_col=[0])
full = full.loc[:, ~full.columns.str.contains('^Unnamed')]
full.head()

,Name,Inspection_Date,Description,City,Longitude,Latitude,Inspection_Type,Inspection_Score,Inspection_Result,Inspection_Closed_Business,Violation_Type,Violation_Description,Violation_Points,Grade,Year,Month,day_of_week,Season
0,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,BLUE,"3200 - Insects, rodents, animals not present; ...",5,1.0,2022,8,Wednesday,Summer
1,#807 TUTTA BELLA,2022-08-31,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,10.0,Unsatisfactory,False,RED,0200 - Food Worker Cards current for all food ...,5,1.0,2022,8,Wednesday,Summer
2,#807 TUTTA BELLA,2022-01-13,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0,2022,1,Thursday,Winter
3,#807 TUTTA BELLA,2021-01-06,Seating 0-12 - Risk Category III,SEATTLE,-122.296415,47.662311,Routine Inspection/Field Review,0.0,Satisfactory,False,No_card,No_violation,0,1.0,2021,1,Wednesday,Winter
4,+MAS CAFE,2022-07-13,Seating 0-12 - Risk Category III,SEATTLE,-122.334587,47.648180,Return Inspection,0.0,Satisfactory,False,No_card,No_violation,0,2.0,2022,7,Wednesday,Summer